In [1]:
import numpy as np

In [19]:
a = np.random.normal(loc=5, size=10, scale=20)
a

array([-18.68550265,  18.31827134,  10.58487392, -31.72081127,
        15.39239075,  14.10778795, -17.38985137,   4.22145958,
         0.34513024,  14.73545301])

In [8]:
b = np.random.normal(loc=5, size=10, scale=20)
b

array([ 26.17610886,   9.93727227,  25.00749532,  19.79352394,
        13.47121015,  22.20512653,  14.65068749,  14.07169198,
       -13.80402136, -26.88099873])

In [15]:
b=b.reshape(10,1)

In [21]:
a=a.reshape(1,10)

In [22]:
np.matmul(a,b)

array([[-745.8642842]])